### ISSUE TITLE
用魔然辅筛方案不出现候选词

### ISSUE THREAD

**Issue by jdjxk** [amorphobia/rabbit#5]
https://github.com/ksqsf/rime-moran
魔然辅筛不出候选词，其他方案正常，小狼毫正常

**Comment by amorphobia** [comment]
![图片](https://github.com/user-attachments/assets/40d62cd7-0baa-47b4-b16c-f742f4dc0351)

你好，我尝试下载了魔然 [2.0.2 版本](https://github.com/ksqsf/rime-moran/releases/download/2.0.2/Moran-Simp-v2.0.2.zip)，应该是可以正常输入的

可否删除 `Rime` 文件夹里的所有内容，然后把魔然压缩包里的所有文件解压到 `Rime` 文件夹再试试？

**Comment by amorphobia** [comment]
同时，你也可以右键托盘图标，打开日志文件夹，看看有无错误日志

**Comment by jdjxk** [comment]
感谢提醒，误删了一个词库文件。
另外请问 Data 目录的作用，好像删除也未影响功能。

**Comment by amorphobia** [comment]
太棒了

> 另外请问 Data 目录的作用

预设的一些配置和方案，如果 `Rime` 目录中有同名的文件，会覆盖 `Data` 中的配置，和小狼毫安装目录中的 `data` 文件夹或者仓输入法的 `SharedData` 作用是一样的

有的配置是必要的，除非自己在在 `Rime` 目录里提供，因此在磁盘空间足够的情况下，不建议删除
